### ISSUE TITLE
Using ES module of date-fns

### ISSUE THREAD

**Issue by sanyi3k** [sapozhnikovay/ngx-mat-datefns-date-adapter#4]
Would it be possible to use the date-fns/locale imports from the ES module of date-fns?
https://date-fns.org/v2.0.0-alpha.6/docs/ECMAScript-Modules

We have an Angular 10 application and the CLI flags a warning due to CommonJS dep:
WARNING in *****\node_modules\ngx-mat-datefns-date-adapter\__ivy_ngcc__\fesm2015\ngx-mat-datefns-date-adapter.js depends on 'date-fns/locale'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by sapozhnikovay** [comment]
Hello, Sándor. 
Current way to import all locales from the date-fns is aimed on simplicity for the language change. It can be improved, there are 2 ways as I see it for the locales import:
- I can leave the import of required date-fns locales completely to the user.
- I can import all available locales from date-fns/esm/locale package but it will require updates the available locales list in the next versions of this package according to date-fns future locale changes.
I need some time to evaluate the right way to deal with the described problem.)

**Comment by sanyi3k** [comment]
Hello!

From my point of view leaving the import of locales to the users seems completely viable, because if you use this adapter, probably you are using date-fns (as the user)
Then it is up to the user if she/he imports it as ESmodule or not.
With it you can decouple from date-fns future locale changes

**Comment by sapozhnikovay** [comment]
Hello.

I've published 11.1.0-beta.0 version to npm. Please, check if there are any issues left with your setup.
You can install beta version with this command:
`npm I ngx-mat-datefns-date-adapter@11.1.0-beta.0`

More info on using it with the new locale imports here:
https://github.com/sapozhnikovay/ngx-mat-datefns-date-adapter/blob/master/projects/ngx-mat-datefns-date-adapter/README.md

Stackblitz example with the new API is here:
https://stackblitz.com/edit/angular-ngx-mat-datefns-date-adapter-a11-es-locales?file=src/app/app.component.ts

I'll release 11.1.0. version and update main README.md and example if there will be no major issues with your project.

**Comment by sanyi3k** [comment]
Hello, 

Thanks for your effort, we will try it out in our test environment.
I will let you know our findings if we have any.

**Comment by illbexyz** [comment]
Hello @sapozhnikovay,

I have been testing the `11.1.0-beta.0` in one of my company's project and it's working like a charm 😃

**Comment by sanyi3k** [comment]
Same results, working well

**Comment by sapozhnikovay** [comment]
@illbexyz , @sanyi3k
Thanks for the evaluation efforts. I've released full 11.1.0 package to npm und updated this repo.
I'll update packages for Angular versions 9/10 later ⏳
