### ISSUE TITLE
Locale dependent date format

### ISSUE THREAD

**Issue by talbx** [sapozhnikovay/ngx-mat-datefns-date-adapter#5]
Hello,

in my current project we are using angular material and momentjs. Thefore we use the material-moment-adapter.
Since we want to switch to date-fns we found this library and tried migrating to it. Everything works fine so far except for the display of the selected Dates. The material-moment-adapter provides the needed functionality.

As shown in your stackblitz examples, when switching the locale, only the date picker itself changes texts, eg the name of the months. What will always stay the same is the selected Date format in the text field which looks like DD/MM/YYYY.

Since it is a vital requirement for us to have the correct date format according to the locale, Im asking if you guys planned to provide such functionality or can give a hint how to achieve this. We are looking for something like

en-US: MM/DD/YYYY
de-DE: DD.MM.YYYY
fr: DD/MM/YYYY

Thanks in advance

**Comment by sapozhnikovay** [comment]
Hello, @talbx .

Thank you for the improvement idea. I'll look into the issues, that are not allowing to properly format the date according to the selected locale. It'll take a couple of days I suppose.

**Comment by hypery2k** [comment]
any plans to add this feature?

**Comment by sapozhnikovay** [comment]
Martin, yep. But it will require a little bit more time due to the my full-time occupation. PRs are welcomed anyway)

**Comment by sapozhnikovay** [comment]
@talbx @hypery2k
It's look like there is a way to achieve the desired functionality with the current state of the date-fns adapter. You need to set the correct value for the MAT_DATE_FORMATS injection tokens. It will use supplied values to parse/format dates in the material Datepicker.

Example:
    {
      provide: MAT_DATE_FORMATS,
      useValue: {
        parse: {
          dateInput: 'P',
        },
        display: {
          dateInput: 'P',
          monthYearLabel: 'MMM yyyy',
          dateA11yLabel: 'PP',
          monthYearA11yLabel: 'MMMM yyyy',
        },
      }
    }
    
Here is a stackblitz example:
https://stackblitz.com/edit/angular-ngx-mat-datefns-date-adapter-a11-es-locales-8itqkj?file=src/app/app.module.ts

I can include parameters in the example as defaults in the package. They are set to mimic [material-moment-adapter defaults](https://github.com/angular/components/blob/ad248652e7da31398176fe11878b59805e440b5a/src/material-moment-adapter/adapter/moment-date-formats.ts).

Please, let me know if this helps with your problem and I'll update the packages on npm with this fix.

**Comment by sapozhnikovay** [comment]
I've updated in 11.2.0 default MAT_DATE_FORMATS value to make locale depended behaviour permanent.
