### ISSUE TITLE
Replicate MatMomentDateModule's useUtc functionality

### ISSUE THREAD

**Issue by yuri1969** [sapozhnikovay/ngx-mat-datefns-date-adapter#6]
Hello,
`MatMomentDateModule` features a [useUtc](https://v11.material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings) flag used in `MAT_MOMENT_DATE_ADAPTER_OPTIONS`. This forces any datepicker to produce dates in UTC regardless of local time zone. So the produced start-of-the-day dates would end exactly with `00:00:00.000Z`.

Is there a way to replicate this behavior using **date-fns**?

**Comment by sapozhnikovay** [comment]
Hello,

I suppose, you mean that with this flag MomentJS will parse any provided string input as UTC date. I think it is possible with the help of [date-fns-tz](https://github.com/marnusw/date-fns-tz#zonedtimetoutc)

I'll look into the possible solution and bring here a stackblitz example.

Right now you can try this code sample on [Runkit ](https://npm.runkit.com/date-fns) to check if this is a desired behaviour:
```
var dateFns = require("date-fns");
var dateFnsTz = require("date-fns-tz");

const d = dateFns.parse('2020-11-1', 'yyyy-MM-dd', new Date());
// Set the input date as taken in a 'UTC' zone - this is a fake.
const timeZone = 'UTC';
// Convert Date into UTC timezone
const d2 = dateFnsTz.zonedTimeToUtc(d, timeZone);
console.log('==== before ====');
console.log(d, d.toUTCString());
console.log('==== after ====');
console.log(d2, d2.toUTCString());
```

**Comment by yuri1969** [comment]
Thanks. Using **date-fns-tz** works as intended. It would be nice to have that option built in.

**Comment by sapozhnikovay** [comment]
Added useUtc flag in 11.2.0.
