### ISSUE TITLE
Warning regarding deep imports during ngcc run

### ISSUE THREAD

**Issue by MichaelKaaden** [sapozhnikovay/ngx-mat-datefns-date-adapter#8]
Since version 11.2.0, running `ngcc --properties es2015 browser module main` produces the following warning message:

`Warning: Entry point 'ngx-mat-datefns-date-adapter' contains deep imports into '<base-path>/<project-name>/node_modules/date-fns-tz/esm'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

Until version 11.1.0, this warning did _not_ appear, and I'm unsure if this might be a real problem or not.

To reproduce, I created a minimal example with Angular 11 and Angular Material 11 that shows a text line with the current time and a DatePicker dialog. Please see https://github.com/MichaelKaaden/ngx-mat-datefns-date-adapter-issue.git. After installing the packages with either Yarn or NPM, the postinstall script with the ngcc call is run triggering the warning.

**Comment by sapozhnikovay** [comment]
Hello, Michael.

Thanks for the comprehensive bug report!) I'll look into this issue and let you know. Perhaps it is connected with the fact that there is really an import from the umd module from `date-fns-tz`.

In 11.2.0 `date-fns-tz` lib have been added to allow mimic of 'UTC' mode from the `moment-date-adapter` (the dates are created with the 00:00:00 time in UTC zone).

Maybe it is connected to this [issue](https://github.com/angular/angular/issues/35615):

**Comment by sapozhnikovay** [comment]
Hi Michael,

I've updated the package to version 11.2.1. I've removed the deep import from the date-fns-tz/esm. According to the [Bundlephobia](https://bundlephobia.com/result?p=date-fns-tz@1.1.4) `date-fns-tz` is tree-shakable, so it will not add too much overhead to the app bundle. I've checked the example you provided with the 11.2.1 version and ngcc throws no more warning messages. At least for now)
Please, check if there are any issues in your project with the new 11.2.1 and let me know.

Best regards,
Alexey.

**Comment by MichaelKaaden** [comment]
Hi Alexey,

just gave it a try, and it works perfectly for me. Many thanks for the quick and thorough fix!

Best regards,
Michael
